name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Deploy to Main
        env:
          SCREEPS_CONFIG: ${{secrets.SCREEPS_CONFIG}}

        run: npm run deploy --environment="production"
